version: '3.8'

services:
  spring-boot-app:
    image: huyandres2001/mdm-be:1.0.1
    container_name: mdm-be
    ports:
      - "8002:8002"
    depends_on:
#      - mongodb   comment by PVH
      - mariadb

  react-app:
    image: huyandres2001/mdm-fe:1.0.0
    container_name: mdm-fe
    ports:
      - "3001:3001"

#  mongodb:
#    image: mongo:latest
#    container_name: notification
#    ports:
#      - "27017:27018"
#    volumes:
#      - mongodb_data:/data/db
#    networks:
#      - backend-network
#   comment by pvh

  mariadb:
    image: mariadb:latest
    container_name: mdm-be-db
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mdm_equipment
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    networks:
      - backend-network
volumes:
  mongodb_data:
  mariadb_data:

networks:
  backend-network:
    driver: bridge
