keycloak:
  port: 8080
  address: http://localhost
  server: ${keycloak.address}:${keycloak.port}
  realm-name: mdm-local
  client-id: api-gateway
  client-secret: 4ICrxzAzPDQa4QKxh9AE8GlB8mGduJ1q
#  4ICrxzAzPDQa4QKxh9AE8GlB8mGduJ1q
#  0SfQyERviyX6Mal4QuTzT3ZOF7W939Wj
  admin:
    username: admin
    password: 123456
    realm-name: master
    client-id: admin-cli
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server}/realms/${keycloak.realm-name}
          jwk-set-uri: ${keycloak.server}/realms/${keycloak.realm-name}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mariadb://localhost:3307/mdm_equipment
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    mongodb:
      database: notification
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: duongbach20231@gmail.com
    password: elxuzbqqgkrwzjor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8002