package com.mdm.equipmentservice.constant;

public class EquipmentExcelConstant {

    public static final String[] EQUIPMENT_COLUMN_HEADER = {
            "STT",
            "Tên thiết bị",
            "Model",
            "Serial",
            "Mã thiết bị",
            "HashCode",
            "Mức độ rủi ro",
            "Thông số kỹ thuật",
            "Ngày nhập kho",
            "Năm sản xuất",
            "Năm sử dụng",
            "Cấu hình",
            "Giá nhập",
            "Giá trị ban đầu",
            "Khấu hao hàng năm",
            "Quy trình sử dụng",
            "Ghi chú",
            "Trạng thái",
            "Nhà sản xuất",
            "Nước sản xuất",
            "Tên loại thiết bị",
            "Tên nhóm loại thiết bị",
            "Tên phòng ban",
            "Chu kì bảo trì",
            "Chu kì kiểm định",
            "Chu kì kiểm xạ",
            "Chu kì ngoại kiểm",
            "Chu kì kiểm định môi trường phòng",
            "Chu kì Gia hạn giấy phép tiến hành tra bức xạ CV định kỳ",
            "Ngày hết hạn hợp đồng liên doanh",
            "Ngày hết hạn bảo hành",
            "Tên dự án",
            "Tên nhà cung cấp dich vụ",
            "Tên đơn vị"
    };

    public static final String[] EQUIPMENT_SETTER = {
            "Id",
            "Name",
            "Model",
            "Serial",
            "Code",
            "HashCode",
            "RiskLevel",
            "TechnicalParameter",
            "WarehouseImportDate",
            "YearOfManufacture",
            "YearInUse",
            "Configuration",
            "ImportPrice",
            "InitialValue",
            "AnnualDepreciation",
            "UsageProcedure",
            "Note",
            "Status",
            "Manufacturer",
            "ManufacturingCountry",
            "CategoryName",
            "CategoryGroupName",
            "DepartmentName",
            "RegularMaintenance",
            "RegularInspection",
            "RegularRadiationInspection",
            "RegularExternalQualityAssessment",
            "RegularClinicEnvironmentInspection",
            "RegularCVRadiation",
            "JointVentureContractExpirationDate",
            "WarrantyExpirationDate",
            "UnitName"
    };
}
